name: build PDF 1 complete volume and 6 single volumes

# controls when the action will run.
# workflow_dispatch: manual triggering
# push: triggers the workflow on push request events but only for the main branch
on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-22.04
    # runs-on: ubuntu-latest
    steps:

    - name: print start date
      run: date +%Y-%m-%d_%H:%M

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # 0 if you want to push to repo

    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

#    - name: setup environment to DE lang
#      run: |
#        cd /usr/share/locales
#        sudo ./install-language-pack de_DE.UTF-8

    - name: test ls before
      run: |
        pwd
        ls -l

    - name: quality check of chapters for known issues
      run: python3 scripts/check-chapters.py

    - name: install requirements
      run: |
        sudo apt update > /dev/null
        sh scripts/install_requirements_pdf.sh > /dev/null

    - name: print versions
      run: |
        cat /etc/os-release
        xelatex -v
        latexmk -v
        # pandoc -v
        python3 --version

    - name: make PDF complete vol
      run: latexmk hpmor > /dev/null
    - name: make PDF vol 1
      run: latexmk hpmor-1 > /dev/null
    - name: make PDF vol 2
      run: latexmk hpmor-2 > /dev/null
    - name: make PDF vol 3
      run: latexmk hpmor-3 > /dev/null
    - name: make PDF vol 4
      run: latexmk hpmor-4 > /dev/null
    - name: make PDF vol 5
      run: latexmk hpmor-5 > /dev/null
    - name: make PDF vol 6
      run: latexmk hpmor-6 > /dev/null

    - name: publish PDFs to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: |
          ./hpmor*.pdf

    - name: print end date
      run: date +%Y-%m-%d_%H:%M
