name: build eBooks

# controls when the action will run.
# workflow_dispatch: manual triggering
# push: triggers the workflow on push request events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-22.04
    # runs-on: ubuntu-latest
    steps:

    - name: print start date
      run: date +%Y-%m-%d_%H:%M

    - name: checkout repository
      uses: actions/checkout@v3

    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: test ls before
      run: |
        pwd
        ls -l

    - name: quality check of chapters for known issues
      run: python3 scripts/check-chapters.py

    # - name: install requirements
    #   run: |
    #     sudo apt update > /dev/null
    #     sh scripts/install_requirements_ebook.sh > /dev/null

    - name: install packages using cache
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: texlive-extra-utils pandoc calibre imagemagick ghostscript
        version: 1.0
        # execute_install_scripts: true

    - name: print versions
      run: |
        cat /etc/os-release
        # xelatex -v
        # latexmk -v
        calibre --version
        pandoc --version
        python3 --version

    # - name: Run pre-commit tests
    #   uses: pre-commit/action@v3.0.0

    - name: download latest PDF
      run:
        wget --quiet https://github.com/entorb/hpmor-de/releases/download/WorkInProgress/hpmor.pdf  -O hpmor.pdf
    #   run: sh scripts/make_pdfs.sh > /dev/null

    - name: make eBooks
      run: |
        sh scripts/make_ebooks.sh > /dev/null

    - name: test ls after
      run: |
        pwd
        ls -l

    - name: publish eBooks to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: |
          ./hpmor.docx
          ./hpmor.html
          ./hpmor.epub
          ./hpmor.mobi
          ./hpmor.fb2

    - name: print end date
      run: date +%Y-%m-%d_%H:%M
